dist: focal
sudo: true

language: go

go:
  - 1.12.x
  - 1.13.x
  - 1.14.x

env:
  - GO111MODULE=on

before_install:
  - . ./build_lxd_test.sh

install: true

before_script:
  - sleep 15
  - go vet

script:
  - go test